package com.example.administrator.mvp.model.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

/**
 * Entity mapped to table "PREVIEW".
 */
public class Preview implements Serializable {

    @Expose
    public Long id;
    @Expose
    public String newsID;
    @SerializedName("Type")
    public int type;
    @SerializedName("Body")
    public String body;
    @SerializedName("Body1")
    public String body1;
    @SerializedName("Body2")
    public String body2;
    @SerializedName("Time")
    public String time;
    @Expose
    private long localCategory;
    @Expose
    public String extraString01;
    @Expose
    public String extraString02;
    @Expose
    public Long extraLong01;
    @Expose
    public Long extraLong02;

    public Preview() {
    }

    public Preview(Long id) {
        this.id = id;
    }


    public Preview(Long id, String newsID, Integer type, String body, String time, long localCategory, String extraString01, String extraString02, Long extraLong01, Long extraLong02) {
        this.id = id;
        this.newsID = newsID;
        this.type = type;
        this.body = body;
        this.time = time;
        this.localCategory = localCategory;
        this.extraString01 = extraString01;
        this.extraString02 = extraString02;
        this.extraLong01 = extraLong01;
        this.extraLong02 = extraLong02;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNewsID() {
        return newsID;
    }

    public void setNewsID(String newsID) {
        this.newsID = newsID;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public String getBody1() {
        return body1;
    }

    public void setBody1(String body1) {
        this.body1 = body1;
    }

    public String getBody2() {
        return body2;
    }

    public void setBody2(String body2) {
        this.body2 = body2;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public long getLocalCategory() {
        return localCategory;
    }

    public void setLocalCategory(long localCategory) {
        this.localCategory = localCategory;
    }

    public String getExtraString01() {
        return extraString01;
    }

    public void setExtraString01(String extraString01) {
        this.extraString01 = extraString01;
    }

    public String getExtraString02() {
        return extraString02;
    }

    public void setExtraString02(String extraString02) {
        this.extraString02 = extraString02;
    }

    public Long getExtraLong01() {
        return extraLong01;
    }

    public void setExtraLong01(Long extraLong01) {
        this.extraLong01 = extraLong01;
    }

    public Long getExtraLong02() {
        return extraLong02;
    }

    public void setExtraLong02(Long extraLong02) {
        this.extraLong02 = extraLong02;
    }

    @Override
    public String toString() {
        return "Preview{" +
                "id=" + id +
                ", newsID=" + newsID +
                ", type=" + type +
                ", time='" + time + '\'' +
                ", localCategory=" + localCategory +
                ", extraString01='" + extraString01 + '\'' +
                ", extraString02='" + extraString02 + '\'' +
                ", extraLong01=" + extraLong01 +
                ", extraLong02=" + extraLong02 +
                '}';
    }
}
