package com.example.administrator.mvp.model.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CATEGORY".
 */
public class Category {

    private Long id;
    private long ID;
    /** Not-null value. */
    private String Category;

    public Category() {
    }

    public Category(Long id) {
        this.id = id;
    }

    public Category(Long id, long ID, String Category) {
        this.id = id;
        this.ID = ID;
        this.Category = Category;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getID() {
        return ID;
    }

    public void setID(long ID) {
        this.ID = ID;
    }

    /** Not-null value. */
    public String getCategory() {
        return Category;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory(String Category) {
        this.Category = Category;
    }

}
