package com.example.administrator.mvp.model.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PREVIEW".
 */
public class Preview {

    private Long id;
    private String NewsID;
    private Integer Type;
    private String Body;
    private String Body1;
    private String Body2;

    public Preview() {
    }

    public Preview(Long id) {
        this.id = id;
    }

    public Preview(Long id, String NewsID, Integer Type, String Body, String Body1, String Body2) {
        this.id = id;
        this.NewsID = NewsID;
        this.Type = Type;
        this.Body = Body;
        this.Body1 = Body1;
        this.Body2 = Body2;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNewsID() {
        return NewsID;
    }

    public void setNewsID(String NewsID) {
        this.NewsID = NewsID;
    }

    public Integer getType() {
        return Type;
    }

    public void setType(Integer Type) {
        this.Type = Type;
    }

    public String getBody() {
        return Body;
    }

    public void setBody(String Body) {
        this.Body = Body;
    }

    public String getBody1() {
        return Body1;
    }

    public void setBody1(String Body1) {
        this.Body1 = Body1;
    }

    public String getBody2() {
        return Body2;
    }

    public void setBody2(String Body2) {
        this.Body2 = Body2;
    }

}
